package com.example.airportv3.entity.enums;

public enum FlightState {
    REGISTERED,
    CREW_MEMBERS_REGISTERED,
    SELLING_TICKETS,
    SOLD,
    DEPARTURE_INITIATED,
    TECH_PREP_COMPLETE,
    CLIENT_CHECK,
    CLIENTS_CHECKED,
    CLIENTS_BRIEFING,
    CLIENTS_BRIEFED,
    CLIENTS_READY,
    CREW_READY,
    DEPARTURE_READY,
    DEPARTURE_CONFIRMED,
    FLIGHT_STARTED,
    FLIGHT_FOOD_DISTRIBUTION,
    FLIGHT_FOOD_DISTRIBUTED,
    LANDING_REQUESTED,
    LANDING_PENDING_CONFIRMATION,
    LANDING_CONFIRMED,
    ARRIVED
}
